sudo: true
services:
 - docker
language: python
python:
  - 2.7
  - 3.2
  - 3.5
install:
  - ./build.sh
before_script:
  - docker version
  - docker info
script:
  - docker ps | grep -q AzureDiskInspectSvc_US
